name: Full CORS & GraphQL Audit

on:
  workflow_dispatch:

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pillow pytesseract

      - name: Install tesseract (optional for OCR)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tesseract-ocr

      - name: Run recon probe
        env:
          ATTACKER_ORIGIN: ${{ secrets.ATTACKER_ORIGIN }}
          TEST_COOKIE: ${{ secrets.TEST_COOKIE }}
          AUTH_BEARER: ${{ secrets.AUTH_BEARER }}
          SESSION_COOKIE: ${{ secrets.SESSION_COOKIE }}
        run: |
          python scripts/recon_probe.py

      - name: Finalize audit decisions
        run: |
          python scripts/audit_finalize.py

      - name: Generate PoCs for HIGH
        run: |
          python scripts/generate_pocs.py

      - name: Prepare archive
        run: |
          ls -lah out || true
          ls -lah pocs || true
          zip -r out/artifacts.zip out pocs || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cors-audit-artifacts
          path: |
            out/findings.json
            out/findings.csv
            out/decision.csv
            out/artifacts.zip
            pocs/
            out/raw/
