name: scan
on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type exactly **true** to confirm you have written authorization to scan these targets'
        required: true
        default: 'False'

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate manual confirmation
        run: |
          echo "[*] confirm input: '${{ github.event.inputs.confirm }}'"
          if [ "${{ github.event.inputs.confirm }}" != "True" ]; then
            echo " ERROR: must type exactly 'True' (case-sensitive) to proceed."
            exit 1
          fi

      - name: Show repo root and contents (debug)
        run: |
          pwd
          ls -R .

      - name: Validate presence of essential files
        run: |
          missing=0
          for f in scan.sh smart_hunt.py vendor_fingerprints.py hosts.txt; do
            if [ ! -f "$f" ]; then
              echo " ERROR: Required file '$f' not found in repo root."
              missing=1
            fi
          done
          if [ "$missing" -eq 1 ]; then
            echo " Aborting due to missing files."
            exit 1
          fi

      - name: Make scan.sh executable
        run: chmod +x scan.sh

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq dnsutils unzip git build-essential
          python3 -m pip install --upgrade pip
          pip3 install aiohttp tldextract
        shell: bash

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Cache Go and nuclei templates
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ${{ github.workspace }}/go/pkg/mod
            ~/.nuclei-templates
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Install optional Go tools
        run: |
          echo "$HOME/go/bin" >> $GITHUB_PATH
          go install github.com/projectdiscovery/httpx/cmd/httpx@latest || true
          go install github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest || true
          go install github.com/owasp-amass/amass/v4/...@latest || true
          if command -v nuclei >/dev/null 2>&1; then
            nuclei -update-templates -silent || true
          fi
        shell: bash

      - name: Run the scan
        env:
          SCAN_CONFIRM: "True"
          GLOBAL_CONCURRENCY: "6"
          PER_TARGET_CONCURRENCY: "6"
          HTTPX_THREADS: "40"
          NUCLEI_RATE_LIMIT: "80"
          NUCLEI_THREADS: "40"
        run: |
          set -euxo pipefail
          echo "[*] Running scan.sh script"
          ./scan.sh
        shell: bash

      - name: Upload findings
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: findings
          path: findings/
