name: scan

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type True (case-sensitive) to confirm you have written authorization to scan targets in hosts.txt"
        required: true
        default: "False"

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 420
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq dnsutils unzip git build-essential
          python3 -m pip install --upgrade pip
          pip3 install aiohttp tldextract

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install Go tools
        run: |
          echo "$HOME/go/bin" >> $GITHUB_PATH
          go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          go install -v github.com/projectdiscovery/dnsx/cmd/dnsx@latest
          go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
          go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
          go install -v github.com/owasp-amass/amass/v4/...@latest
          nuclei -update-templates -silent || true

      - name: Make scripts executable
        run: chmod +x scan.sh

      - name: Run scan (requires manual confirm=True)
        env:
          SCAN_CONFIRM: ${{ github.event.inputs.confirm }}
          GLOBAL_CONCURRENCY: "10"         # across roots
          PER_TARGET_CONCURRENCY: "12"     # inside smart checks
          AMASS_TIMEOUT_MIN: "10"
          SUBFINDER_SOURCES: "all"
          DNSX_WORKERS: "200"
          HTTPX_THREADS: "150"
          HTTPX_TIMEOUT: "8"
          NUCLEI_THREADS: "120"
          NUCLEI_RATE_LIMIT: "200"
          # smart filter knobs
          MAX_URLS_PER_HOST: "2000"
          PATH_CHECK_TOP_HOSTS: "200"      # most interesting hosts by httpx signals
        run: ./scan.sh

      - name: Upload findings
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: findings
          path: findings/
