name: aggressive-scan

on:
  workflow_dispatch:
    inputs:
      run_targets:
        description: 'Comma-separated targets (optional). If empty uses hosts.txt'
        required: false
        default: ''

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 dnspython httpx tldextract

      - name: Run scan
        env:
          RUN_TARGETS: ${{ github.event.inputs.run_targets }}
        run: |
          chmod +x scripts/scan_all.sh
          ./scripts/scan_all.sh

      - name: Upload findings
        uses: actions/upload-artifact@v4
        with:
          name: aggressive-scan-findings
          path: findings/
