name: scan
on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type True (case-sensitive) to confirm you have written authorization to scan targets in hosts.txt'
        required: true
        default: 'False'

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq dnsutils unzip git build-essential
          python3 -m pip install --upgrade pip
          pip3 install aiohttp tldextract

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install Go tools (httpx, nuclei, amass) - optional
        run: |
          echo "$HOME/go/bin" >> $GITHUB_PATH
          go install github.com/projectdiscovery/httpx/cmd/httpx@latest || true
          go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest || true
          go install -v github.com/owasp-amass/amass/v4/...@latest || true
          # update nuclei templates if installed
          if command -v nuclei >/dev/null 2>&1; then
            nuclei -update-templates -silent || true
          fi

      - name: Make scripts executable
        run: chmod +x scan.sh

      - name: Run scan (requires manual confirm = True)
        env:
          # pass the manual input to the script
          SCAN_CONFIRM: ${{ github.event.inputs.confirm }}
          GLOBAL_CONCURRENCY: "6"
          PER_TARGET_CONCURRENCY: "6"
          HTTPX_THREADS: "40"
          NUCLEI_RATE_LIMIT: "80"
          NUCLEI_THREADS: "40"
        run: |
          echo "[*] confirm value: $SCAN_CONFIRM"
          ./scan.sh

      - name: Upload findings (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: findings
          path: findings/
